(docs) Updated building instructions
valorkin/module-federation pull request #41
Opened 2021-05-12 13:37 UTC by omfgnuts

Updated building instructions according to current project status, cross-linked with other docs

2021-05-14 11:37 UTC, nowant requested changes

2021-05-14 11:37 UTC, nowant commented on README.md
> +## Tech Stack
Stack of what ? Demo apps or libs, or both?

2021-05-14 11:37 UTC, nowant commented on README.md
> +- NgRx
We use Ngrx in the one demo app, it's not a part of Module Federation feature. Should we actually point it here?

2021-05-14 11:37 UTC, nowant commented on README.md
> +Each application contains `webpack.extra.js` that extends existing Angular CLI builder with ability to hook up custom Webpack plugin. In `webpack.extra.js`  we define specifics for the _Module federa
`Each application contains 'webpack.extra.js' that extends existing Angular CLI builder`
Don't get it. `webpack.extra.js` doesn't extend Angular CLI, it is used to configure Webpack ModuleFederationPlugin to expose components and attach remote urls. Angular CLI consumes `webpack.extra.js` and not vice versa.

2021-05-14 11:37 UTC, nowant commented on README.md
> +- NgRx
And I think we should to add: `Angular CLI`, `ngx-build-plus`, `Webpack`/`ModuleFederationPlugin`. Since these are the main packages that provide us with the entire MF functionality

2021-05-14 13:49 UTC, omfgnuts commented on README.md
> +## Tech Stack
Both. Cleaned up some more

2021-05-17 09:38 UTC, nowant approved these changes

2022-06-30 11:17 UTC, closed without merging